name: Build and publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: Publish the image to GHCR
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-app.yaml
    with:
      app: "ha_extractor"
      publish: ${{ github.event_name == 'push' || inputs.publish == true }}
    secrets: inherit
